spring:
  datasource:
    url: jdbc:postgresql://${POSTGRES_SERVER}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driverClassName: org.postgresql.Driver
    platform: postgres
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: true
  main:
    allow-bean-definition-overriding: true

server:
  servlet:
    context-path: /cars
  port: 3030

feign:
  hystrix:
    enabled: true

security:
  oauth2:
    client:
      client-id: book-service
      client-secret: ${BOOK_SERVICE_PASSWORD}
      access-token-uri: http://auth-service:5001/uaa/oauth/token
      grant-type: client_credentials
      scope: server
