spring:
  mail:
    properties:
      mail:
        smtp:
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000
    debug: true
    default-encoding: UTF-8

    host: srv-plesk61.ps.kz
    password: 486o8ozD_
    port: 465
    protocol: smtps
    smtp:
      auth: true
      starttls:
        enable: true
    username: no-reply@utools.kz

server:
  servlet:
    context-path: /mail

security:
  oauth2:
    client:
      client-id: mail-service
      client-secret: ${MAIL_SERVICE_PASSWORD}
      access-token-uri: http://auth-service:5001/uaa/oauth/token
      grant-type: client_credentials
      scope: server
